### ISSUE TITLE
Informabot: Error: ENOENT: no such file or directory, open 'json/groups.json'

### ISSUE THREAD

**Issue by foxyseta** [csunibo/infrastructure#1]
@csunibo/sistemisti Come segnalato da @LiberaLongo, il comando `/cercogruppo` di Informabot non funziona.
```
Error: ENOENT: no such file or directory, open 'json/groups.json'
```

`groups.json` però è presente nel filesystem in quello che dovrebbe essere il posto giusto.

**Comment by lucat1** [comment]
Se lo vuoi sistemare tu (e sarebbe la cosa giusta da fare) devi usare come percorso `path.join(__dirname, '..', 'json', 'groups.json')` che rende il percorso relativo _al file dove hai scritto il codice_. Attualmente cosi e' relativo alla PWD in cui viene lanciato il prorgamma, che e' `src` , puoi controllare [qua](https://github.com/csunibo/infrastructure/blob/main/files/bot/bot.service.j2#L11) . Se non vuoi modificare il codice del bot allora per farlo funzionare come il codice attuale bisogna impostare la `PWD` al padre della attuale, cambiando sempre la linea che ti ho linkato. Penso comunque che la prima soluzione sia piu' sicura.

**Comment by foxyseta** [comment]
Sì, opterò per la prima soluzione. Siccome risolviamo modificando Informabot e non gli ansible chiudo come non pianificata.
