### ISSUE TITLE
Ricompilare e riavviare il bot solo quando viene pullato qualcosa

### ISSUE THREAD

**Issue by foxyseta** [csunibo/infrastructure#3]
Al momento il bot viene ricopiato e il servizio viene riavviato a prescindere. Un'ottimizzazione potrebbe essere quello di effettuare questi due passaggi solo quando effettivamente si applicano uno o più commit nuovi. Ci pensa qualcuno in @csunibo/sistemisti tipo @Flecart ?

**Comment by Flecart** [comment]
si, dovrebbe essere ez, faccio.

**Comment by Flecart** [comment]
#4 solves
